name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11.0'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile

  build:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11.0'
          cache: 'yarn'
      - name: Check node_modules
        run: ls node_modules || yarn install --frozen-lockfile
      - name: Build
        run: yarn build

  linters:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11.0'
          cache: 'yarn'
      - name: Check node_modules
        run: ls node_modules || yarn install --frozen-lockfile
      - name: Run linters
        run: yarn linters

  deploy:
    needs: [dependencies, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11.0'
          cache: 'yarn'
      - name: Check node_modules
        run: ls node_modules || yarn install --frozen-lockfile
      - name: Deploy
        run: yarn deploy